server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/workoutch?verifyServerCertificate=false&useSSL=false&requireSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: app
    password: secret
    test-on-borrow: true
    validation-query: SELECT 1

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      show_sql: true
  thymeleaf:
    cache: false

reportdata:
  update-delay-in-millis: 120000
  reportdata.cleanup-frequency-in-millis: 120000
