server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/WORKOUTCHALLENGERS
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: abc@123
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
      show_sql: true
  thymeleaf:
    cache: false

reportdata:
  update-delay-in-millis: 120000
  reportdata.cleanup-frequency-in-millis: 120000
